### ISSUE TITLE
LTY Feedback - github email test

### ISSUE THREAD

**Issue by BU-MET-EdTech** [BU-MET-EdTech/feedback#39]
**Sender**: yuvarajg@bu.edu
**Comment**: github testing
[Open #39 in Usersnap Dashboard](https://usersnap.com/a/#/met-bu/p/blackboard-feedb/39)

![LTY Feedback - github email test](https://usersnappublic.s3.amazonaws.com/2015-02-18/22-47/c945d29f-4118-452a-a42f-4f7de4c87958.png)

**Browser**: Chrome 40 (Windows 7)
**Referer**: [https://learn.bu.edu/bbcswebdav/pid-2823263-dt-content-rid-9593960_1/courses/14fallmetad671_b1/Module4-1/index.html](https://learn.bu.edu/bbcswebdav/pid-2823263-dt-content-rid-9593960_1/courses/14fallmetad671_b1/Module4-1/index.html)
**IP**: 128.197.101.218
**Screen size**: 1920 x 1200 **Browser size**: 1920 x 1075

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by ltyfaculty** [comment]
feedback resolved
